# Generated by Django 3.1 on 2021-02-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phoneModel',
            new_name='MobilePhone',
        ),
        migrations.RenameField(
            model_name='mobilephone',
            old_name='Mobile',
            new_name='Number',
        ),
    ]
